// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// JobsColumns holds the columns for the "jobs" table.
	JobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "job_id", Type: field.TypeString, Unique: true},
		{Name: "target_node_id", Type: field.TypeString},
		{Name: "command", Type: field.TypeString},
		{Name: "env", Type: field.TypeJSON, Nullable: true},
		{Name: "timeout_seconds", Type: field.TypeInt32, Default: 300},
		{Name: "status", Type: field.TypeString, Default: "JOB_PENDING"},
		{Name: "created_by_node", Type: field.TypeString},
		{Name: "exit_code", Type: field.TypeInt32, Nullable: true},
		{Name: "stdout", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "stderr", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// JobsTable holds the schema information for the "jobs" table.
	JobsTable = &schema.Table{
		Name:       "jobs",
		Columns:    JobsColumns,
		PrimaryKey: []*schema.Column{JobsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "job_job_id",
				Unique:  true,
				Columns: []*schema.Column{JobsColumns[1]},
			},
			{
				Name:    "job_status",
				Unique:  false,
				Columns: []*schema.Column{JobsColumns[6]},
			},
			{
				Name:    "job_target_node_id",
				Unique:  false,
				Columns: []*schema.Column{JobsColumns[2]},
			},
		},
	}
	// WorkerNodesColumns holds the columns for the "worker_nodes" table.
	WorkerNodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "node_id", Type: field.TypeString, Unique: true},
		{Name: "address", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "UNKNOWN"},
		{Name: "last_heartbeat", Type: field.TypeTime},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "version", Type: field.TypeString, Default: "1.0.0"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// WorkerNodesTable holds the schema information for the "worker_nodes" table.
	WorkerNodesTable = &schema.Table{
		Name:       "worker_nodes",
		Columns:    WorkerNodesColumns,
		PrimaryKey: []*schema.Column{WorkerNodesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "workernode_node_id",
				Unique:  true,
				Columns: []*schema.Column{WorkerNodesColumns[1]},
			},
			{
				Name:    "workernode_status",
				Unique:  false,
				Columns: []*schema.Column{WorkerNodesColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		JobsTable,
		WorkerNodesTable,
	}
)

func init() {
}
