// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/retr0-kernel/worker-mesh/ent/job"
)

// JobCreate is the builder for creating a Job entity.
type JobCreate struct {
	config
	mutation *JobMutation
	hooks    []Hook
}

// SetJobID sets the "job_id" field.
func (jc *JobCreate) SetJobID(s string) *JobCreate {
	jc.mutation.SetJobID(s)
	return jc
}

// SetTargetNodeID sets the "target_node_id" field.
func (jc *JobCreate) SetTargetNodeID(s string) *JobCreate {
	jc.mutation.SetTargetNodeID(s)
	return jc
}

// SetCommand sets the "command" field.
func (jc *JobCreate) SetCommand(s string) *JobCreate {
	jc.mutation.SetCommand(s)
	return jc
}

// SetEnv sets the "env" field.
func (jc *JobCreate) SetEnv(m map[string]string) *JobCreate {
	jc.mutation.SetEnv(m)
	return jc
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (jc *JobCreate) SetTimeoutSeconds(i int32) *JobCreate {
	jc.mutation.SetTimeoutSeconds(i)
	return jc
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (jc *JobCreate) SetNillableTimeoutSeconds(i *int32) *JobCreate {
	if i != nil {
		jc.SetTimeoutSeconds(*i)
	}
	return jc
}

// SetStatus sets the "status" field.
func (jc *JobCreate) SetStatus(s string) *JobCreate {
	jc.mutation.SetStatus(s)
	return jc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (jc *JobCreate) SetNillableStatus(s *string) *JobCreate {
	if s != nil {
		jc.SetStatus(*s)
	}
	return jc
}

// SetCreatedByNode sets the "created_by_node" field.
func (jc *JobCreate) SetCreatedByNode(s string) *JobCreate {
	jc.mutation.SetCreatedByNode(s)
	return jc
}

// SetExitCode sets the "exit_code" field.
func (jc *JobCreate) SetExitCode(i int32) *JobCreate {
	jc.mutation.SetExitCode(i)
	return jc
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (jc *JobCreate) SetNillableExitCode(i *int32) *JobCreate {
	if i != nil {
		jc.SetExitCode(*i)
	}
	return jc
}

// SetStdout sets the "stdout" field.
func (jc *JobCreate) SetStdout(s string) *JobCreate {
	jc.mutation.SetStdout(s)
	return jc
}

// SetNillableStdout sets the "stdout" field if the given value is not nil.
func (jc *JobCreate) SetNillableStdout(s *string) *JobCreate {
	if s != nil {
		jc.SetStdout(*s)
	}
	return jc
}

// SetStderr sets the "stderr" field.
func (jc *JobCreate) SetStderr(s string) *JobCreate {
	jc.mutation.SetStderr(s)
	return jc
}

// SetNillableStderr sets the "stderr" field if the given value is not nil.
func (jc *JobCreate) SetNillableStderr(s *string) *JobCreate {
	if s != nil {
		jc.SetStderr(*s)
	}
	return jc
}

// SetErrorMessage sets the "error_message" field.
func (jc *JobCreate) SetErrorMessage(s string) *JobCreate {
	jc.mutation.SetErrorMessage(s)
	return jc
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (jc *JobCreate) SetNillableErrorMessage(s *string) *JobCreate {
	if s != nil {
		jc.SetErrorMessage(*s)
	}
	return jc
}

// SetCreatedAt sets the "created_at" field.
func (jc *JobCreate) SetCreatedAt(t time.Time) *JobCreate {
	jc.mutation.SetCreatedAt(t)
	return jc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (jc *JobCreate) SetNillableCreatedAt(t *time.Time) *JobCreate {
	if t != nil {
		jc.SetCreatedAt(*t)
	}
	return jc
}

// SetStartedAt sets the "started_at" field.
func (jc *JobCreate) SetStartedAt(t time.Time) *JobCreate {
	jc.mutation.SetStartedAt(t)
	return jc
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (jc *JobCreate) SetNillableStartedAt(t *time.Time) *JobCreate {
	if t != nil {
		jc.SetStartedAt(*t)
	}
	return jc
}

// SetFinishedAt sets the "finished_at" field.
func (jc *JobCreate) SetFinishedAt(t time.Time) *JobCreate {
	jc.mutation.SetFinishedAt(t)
	return jc
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (jc *JobCreate) SetNillableFinishedAt(t *time.Time) *JobCreate {
	if t != nil {
		jc.SetFinishedAt(*t)
	}
	return jc
}

// SetUpdatedAt sets the "updated_at" field.
func (jc *JobCreate) SetUpdatedAt(t time.Time) *JobCreate {
	jc.mutation.SetUpdatedAt(t)
	return jc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (jc *JobCreate) SetNillableUpdatedAt(t *time.Time) *JobCreate {
	if t != nil {
		jc.SetUpdatedAt(*t)
	}
	return jc
}

// Mutation returns the JobMutation object of the builder.
func (jc *JobCreate) Mutation() *JobMutation {
	return jc.mutation
}

// Save creates the Job in the database.
func (jc *JobCreate) Save(ctx context.Context) (*Job, error) {
	jc.defaults()
	return withHooks(ctx, jc.sqlSave, jc.mutation, jc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (jc *JobCreate) SaveX(ctx context.Context) *Job {
	v, err := jc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jc *JobCreate) Exec(ctx context.Context) error {
	_, err := jc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jc *JobCreate) ExecX(ctx context.Context) {
	if err := jc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (jc *JobCreate) defaults() {
	if _, ok := jc.mutation.TimeoutSeconds(); !ok {
		v := job.DefaultTimeoutSeconds
		jc.mutation.SetTimeoutSeconds(v)
	}
	if _, ok := jc.mutation.Status(); !ok {
		v := job.DefaultStatus
		jc.mutation.SetStatus(v)
	}
	if _, ok := jc.mutation.CreatedAt(); !ok {
		v := job.DefaultCreatedAt()
		jc.mutation.SetCreatedAt(v)
	}
	if _, ok := jc.mutation.UpdatedAt(); !ok {
		v := job.DefaultUpdatedAt()
		jc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jc *JobCreate) check() error {
	if _, ok := jc.mutation.JobID(); !ok {
		return &ValidationError{Name: "job_id", err: errors.New(`ent: missing required field "Job.job_id"`)}
	}
	if _, ok := jc.mutation.TargetNodeID(); !ok {
		return &ValidationError{Name: "target_node_id", err: errors.New(`ent: missing required field "Job.target_node_id"`)}
	}
	if _, ok := jc.mutation.Command(); !ok {
		return &ValidationError{Name: "command", err: errors.New(`ent: missing required field "Job.command"`)}
	}
	if _, ok := jc.mutation.TimeoutSeconds(); !ok {
		return &ValidationError{Name: "timeout_seconds", err: errors.New(`ent: missing required field "Job.timeout_seconds"`)}
	}
	if _, ok := jc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Job.status"`)}
	}
	if _, ok := jc.mutation.CreatedByNode(); !ok {
		return &ValidationError{Name: "created_by_node", err: errors.New(`ent: missing required field "Job.created_by_node"`)}
	}
	if _, ok := jc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Job.created_at"`)}
	}
	if _, ok := jc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Job.updated_at"`)}
	}
	return nil
}

func (jc *JobCreate) sqlSave(ctx context.Context) (*Job, error) {
	if err := jc.check(); err != nil {
		return nil, err
	}
	_node, _spec := jc.createSpec()
	if err := sqlgraph.CreateNode(ctx, jc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	jc.mutation.id = &_node.ID
	jc.mutation.done = true
	return _node, nil
}

func (jc *JobCreate) createSpec() (*Job, *sqlgraph.CreateSpec) {
	var (
		_node = &Job{config: jc.config}
		_spec = sqlgraph.NewCreateSpec(job.Table, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	)
	if value, ok := jc.mutation.JobID(); ok {
		_spec.SetField(job.FieldJobID, field.TypeString, value)
		_node.JobID = value
	}
	if value, ok := jc.mutation.TargetNodeID(); ok {
		_spec.SetField(job.FieldTargetNodeID, field.TypeString, value)
		_node.TargetNodeID = value
	}
	if value, ok := jc.mutation.Command(); ok {
		_spec.SetField(job.FieldCommand, field.TypeString, value)
		_node.Command = value
	}
	if value, ok := jc.mutation.Env(); ok {
		_spec.SetField(job.FieldEnv, field.TypeJSON, value)
		_node.Env = value
	}
	if value, ok := jc.mutation.TimeoutSeconds(); ok {
		_spec.SetField(job.FieldTimeoutSeconds, field.TypeInt32, value)
		_node.TimeoutSeconds = value
	}
	if value, ok := jc.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := jc.mutation.CreatedByNode(); ok {
		_spec.SetField(job.FieldCreatedByNode, field.TypeString, value)
		_node.CreatedByNode = value
	}
	if value, ok := jc.mutation.ExitCode(); ok {
		_spec.SetField(job.FieldExitCode, field.TypeInt32, value)
		_node.ExitCode = value
	}
	if value, ok := jc.mutation.Stdout(); ok {
		_spec.SetField(job.FieldStdout, field.TypeString, value)
		_node.Stdout = value
	}
	if value, ok := jc.mutation.Stderr(); ok {
		_spec.SetField(job.FieldStderr, field.TypeString, value)
		_node.Stderr = value
	}
	if value, ok := jc.mutation.ErrorMessage(); ok {
		_spec.SetField(job.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := jc.mutation.CreatedAt(); ok {
		_spec.SetField(job.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := jc.mutation.StartedAt(); ok {
		_spec.SetField(job.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := jc.mutation.FinishedAt(); ok {
		_spec.SetField(job.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = value
	}
	if value, ok := jc.mutation.UpdatedAt(); ok {
		_spec.SetField(job.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// JobCreateBulk is the builder for creating many Job entities in bulk.
type JobCreateBulk struct {
	config
	err      error
	builders []*JobCreate
}

// Save creates the Job entities in the database.
func (jcb *JobCreateBulk) Save(ctx context.Context) ([]*Job, error) {
	if jcb.err != nil {
		return nil, jcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(jcb.builders))
	nodes := make([]*Job, len(jcb.builders))
	mutators := make([]Mutator, len(jcb.builders))
	for i := range jcb.builders {
		func(i int, root context.Context) {
			builder := jcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, jcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, jcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, jcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (jcb *JobCreateBulk) SaveX(ctx context.Context) []*Job {
	v, err := jcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jcb *JobCreateBulk) Exec(ctx context.Context) error {
	_, err := jcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jcb *JobCreateBulk) ExecX(ctx context.Context) {
	if err := jcb.Exec(ctx); err != nil {
		panic(err)
	}
}
