// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/retr0-kernel/worker-mesh/ent/job"
	"github.com/retr0-kernel/worker-mesh/ent/schema"
	"github.com/retr0-kernel/worker-mesh/ent/workernode"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	jobFields := schema.Job{}.Fields()
	_ = jobFields
	// jobDescTimeoutSeconds is the schema descriptor for timeout_seconds field.
	jobDescTimeoutSeconds := jobFields[4].Descriptor()
	// job.DefaultTimeoutSeconds holds the default value on creation for the timeout_seconds field.
	job.DefaultTimeoutSeconds = jobDescTimeoutSeconds.Default.(int32)
	// jobDescStatus is the schema descriptor for status field.
	jobDescStatus := jobFields[5].Descriptor()
	// job.DefaultStatus holds the default value on creation for the status field.
	job.DefaultStatus = jobDescStatus.Default.(string)
	// jobDescCreatedAt is the schema descriptor for created_at field.
	jobDescCreatedAt := jobFields[11].Descriptor()
	// job.DefaultCreatedAt holds the default value on creation for the created_at field.
	job.DefaultCreatedAt = jobDescCreatedAt.Default.(func() time.Time)
	// jobDescUpdatedAt is the schema descriptor for updated_at field.
	jobDescUpdatedAt := jobFields[14].Descriptor()
	// job.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	job.DefaultUpdatedAt = jobDescUpdatedAt.Default.(func() time.Time)
	// job.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	job.UpdateDefaultUpdatedAt = jobDescUpdatedAt.UpdateDefault.(func() time.Time)
	workernodeFields := schema.WorkerNode{}.Fields()
	_ = workernodeFields
	// workernodeDescStatus is the schema descriptor for status field.
	workernodeDescStatus := workernodeFields[2].Descriptor()
	// workernode.DefaultStatus holds the default value on creation for the status field.
	workernode.DefaultStatus = workernodeDescStatus.Default.(string)
	// workernodeDescLastHeartbeat is the schema descriptor for last_heartbeat field.
	workernodeDescLastHeartbeat := workernodeFields[3].Descriptor()
	// workernode.DefaultLastHeartbeat holds the default value on creation for the last_heartbeat field.
	workernode.DefaultLastHeartbeat = workernodeDescLastHeartbeat.Default.(func() time.Time)
	// workernodeDescVersion is the schema descriptor for version field.
	workernodeDescVersion := workernodeFields[5].Descriptor()
	// workernode.DefaultVersion holds the default value on creation for the version field.
	workernode.DefaultVersion = workernodeDescVersion.Default.(string)
	// workernodeDescCreatedAt is the schema descriptor for created_at field.
	workernodeDescCreatedAt := workernodeFields[6].Descriptor()
	// workernode.DefaultCreatedAt holds the default value on creation for the created_at field.
	workernode.DefaultCreatedAt = workernodeDescCreatedAt.Default.(func() time.Time)
	// workernodeDescUpdatedAt is the schema descriptor for updated_at field.
	workernodeDescUpdatedAt := workernodeFields[7].Descriptor()
	// workernode.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workernode.DefaultUpdatedAt = workernodeDescUpdatedAt.Default.(func() time.Time)
	// workernode.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workernode.UpdateDefaultUpdatedAt = workernodeDescUpdatedAt.UpdateDefault.(func() time.Time)
}
