// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/retr0-kernel/worker-mesh/ent/predicate"
	"github.com/retr0-kernel/worker-mesh/ent/workernode"
)

// WorkerNodeQuery is the builder for querying WorkerNode entities.
type WorkerNodeQuery struct {
	config
	ctx        *QueryContext
	order      []workernode.OrderOption
	inters     []Interceptor
	predicates []predicate.WorkerNode
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WorkerNodeQuery builder.
func (wnq *WorkerNodeQuery) Where(ps ...predicate.WorkerNode) *WorkerNodeQuery {
	wnq.predicates = append(wnq.predicates, ps...)
	return wnq
}

// Limit the number of records to be returned by this query.
func (wnq *WorkerNodeQuery) Limit(limit int) *WorkerNodeQuery {
	wnq.ctx.Limit = &limit
	return wnq
}

// Offset to start from.
func (wnq *WorkerNodeQuery) Offset(offset int) *WorkerNodeQuery {
	wnq.ctx.Offset = &offset
	return wnq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wnq *WorkerNodeQuery) Unique(unique bool) *WorkerNodeQuery {
	wnq.ctx.Unique = &unique
	return wnq
}

// Order specifies how the records should be ordered.
func (wnq *WorkerNodeQuery) Order(o ...workernode.OrderOption) *WorkerNodeQuery {
	wnq.order = append(wnq.order, o...)
	return wnq
}

// First returns the first WorkerNode entity from the query.
// Returns a *NotFoundError when no WorkerNode was found.
func (wnq *WorkerNodeQuery) First(ctx context.Context) (*WorkerNode, error) {
	nodes, err := wnq.Limit(1).All(setContextOp(ctx, wnq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{workernode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wnq *WorkerNodeQuery) FirstX(ctx context.Context) *WorkerNode {
	node, err := wnq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WorkerNode ID from the query.
// Returns a *NotFoundError when no WorkerNode ID was found.
func (wnq *WorkerNodeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wnq.Limit(1).IDs(setContextOp(ctx, wnq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{workernode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wnq *WorkerNodeQuery) FirstIDX(ctx context.Context) int {
	id, err := wnq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WorkerNode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WorkerNode entity is found.
// Returns a *NotFoundError when no WorkerNode entities are found.
func (wnq *WorkerNodeQuery) Only(ctx context.Context) (*WorkerNode, error) {
	nodes, err := wnq.Limit(2).All(setContextOp(ctx, wnq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{workernode.Label}
	default:
		return nil, &NotSingularError{workernode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wnq *WorkerNodeQuery) OnlyX(ctx context.Context) *WorkerNode {
	node, err := wnq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WorkerNode ID in the query.
// Returns a *NotSingularError when more than one WorkerNode ID is found.
// Returns a *NotFoundError when no entities are found.
func (wnq *WorkerNodeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wnq.Limit(2).IDs(setContextOp(ctx, wnq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{workernode.Label}
	default:
		err = &NotSingularError{workernode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wnq *WorkerNodeQuery) OnlyIDX(ctx context.Context) int {
	id, err := wnq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WorkerNodes.
func (wnq *WorkerNodeQuery) All(ctx context.Context) ([]*WorkerNode, error) {
	ctx = setContextOp(ctx, wnq.ctx, ent.OpQueryAll)
	if err := wnq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WorkerNode, *WorkerNodeQuery]()
	return withInterceptors[[]*WorkerNode](ctx, wnq, qr, wnq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wnq *WorkerNodeQuery) AllX(ctx context.Context) []*WorkerNode {
	nodes, err := wnq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WorkerNode IDs.
func (wnq *WorkerNodeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if wnq.ctx.Unique == nil && wnq.path != nil {
		wnq.Unique(true)
	}
	ctx = setContextOp(ctx, wnq.ctx, ent.OpQueryIDs)
	if err = wnq.Select(workernode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wnq *WorkerNodeQuery) IDsX(ctx context.Context) []int {
	ids, err := wnq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wnq *WorkerNodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wnq.ctx, ent.OpQueryCount)
	if err := wnq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wnq, querierCount[*WorkerNodeQuery](), wnq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wnq *WorkerNodeQuery) CountX(ctx context.Context) int {
	count, err := wnq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wnq *WorkerNodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wnq.ctx, ent.OpQueryExist)
	switch _, err := wnq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wnq *WorkerNodeQuery) ExistX(ctx context.Context) bool {
	exist, err := wnq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WorkerNodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wnq *WorkerNodeQuery) Clone() *WorkerNodeQuery {
	if wnq == nil {
		return nil
	}
	return &WorkerNodeQuery{
		config:     wnq.config,
		ctx:        wnq.ctx.Clone(),
		order:      append([]workernode.OrderOption{}, wnq.order...),
		inters:     append([]Interceptor{}, wnq.inters...),
		predicates: append([]predicate.WorkerNode{}, wnq.predicates...),
		// clone intermediate query.
		sql:  wnq.sql.Clone(),
		path: wnq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		NodeID string `json:"node_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WorkerNode.Query().
//		GroupBy(workernode.FieldNodeID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wnq *WorkerNodeQuery) GroupBy(field string, fields ...string) *WorkerNodeGroupBy {
	wnq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WorkerNodeGroupBy{build: wnq}
	grbuild.flds = &wnq.ctx.Fields
	grbuild.label = workernode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		NodeID string `json:"node_id,omitempty"`
//	}
//
//	client.WorkerNode.Query().
//		Select(workernode.FieldNodeID).
//		Scan(ctx, &v)
func (wnq *WorkerNodeQuery) Select(fields ...string) *WorkerNodeSelect {
	wnq.ctx.Fields = append(wnq.ctx.Fields, fields...)
	sbuild := &WorkerNodeSelect{WorkerNodeQuery: wnq}
	sbuild.label = workernode.Label
	sbuild.flds, sbuild.scan = &wnq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WorkerNodeSelect configured with the given aggregations.
func (wnq *WorkerNodeQuery) Aggregate(fns ...AggregateFunc) *WorkerNodeSelect {
	return wnq.Select().Aggregate(fns...)
}

func (wnq *WorkerNodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wnq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wnq); err != nil {
				return err
			}
		}
	}
	for _, f := range wnq.ctx.Fields {
		if !workernode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wnq.path != nil {
		prev, err := wnq.path(ctx)
		if err != nil {
			return err
		}
		wnq.sql = prev
	}
	return nil
}

func (wnq *WorkerNodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WorkerNode, error) {
	var (
		nodes = []*WorkerNode{}
		_spec = wnq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WorkerNode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WorkerNode{config: wnq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wnq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (wnq *WorkerNodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wnq.querySpec()
	_spec.Node.Columns = wnq.ctx.Fields
	if len(wnq.ctx.Fields) > 0 {
		_spec.Unique = wnq.ctx.Unique != nil && *wnq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wnq.driver, _spec)
}

func (wnq *WorkerNodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(workernode.Table, workernode.Columns, sqlgraph.NewFieldSpec(workernode.FieldID, field.TypeInt))
	_spec.From = wnq.sql
	if unique := wnq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wnq.path != nil {
		_spec.Unique = true
	}
	if fields := wnq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workernode.FieldID)
		for i := range fields {
			if fields[i] != workernode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wnq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wnq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wnq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wnq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wnq *WorkerNodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wnq.driver.Dialect())
	t1 := builder.Table(workernode.Table)
	columns := wnq.ctx.Fields
	if len(columns) == 0 {
		columns = workernode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wnq.sql != nil {
		selector = wnq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wnq.ctx.Unique != nil && *wnq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wnq.predicates {
		p(selector)
	}
	for _, p := range wnq.order {
		p(selector)
	}
	if offset := wnq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wnq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WorkerNodeGroupBy is the group-by builder for WorkerNode entities.
type WorkerNodeGroupBy struct {
	selector
	build *WorkerNodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wngb *WorkerNodeGroupBy) Aggregate(fns ...AggregateFunc) *WorkerNodeGroupBy {
	wngb.fns = append(wngb.fns, fns...)
	return wngb
}

// Scan applies the selector query and scans the result into the given value.
func (wngb *WorkerNodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wngb.build.ctx, ent.OpQueryGroupBy)
	if err := wngb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkerNodeQuery, *WorkerNodeGroupBy](ctx, wngb.build, wngb, wngb.build.inters, v)
}

func (wngb *WorkerNodeGroupBy) sqlScan(ctx context.Context, root *WorkerNodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wngb.fns))
	for _, fn := range wngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wngb.flds)+len(wngb.fns))
		for _, f := range *wngb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wngb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wngb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WorkerNodeSelect is the builder for selecting fields of WorkerNode entities.
type WorkerNodeSelect struct {
	*WorkerNodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wns *WorkerNodeSelect) Aggregate(fns ...AggregateFunc) *WorkerNodeSelect {
	wns.fns = append(wns.fns, fns...)
	return wns
}

// Scan applies the selector query and scans the result into the given value.
func (wns *WorkerNodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wns.ctx, ent.OpQuerySelect)
	if err := wns.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkerNodeQuery, *WorkerNodeSelect](ctx, wns.WorkerNodeQuery, wns, wns.inters, v)
}

func (wns *WorkerNodeSelect) sqlScan(ctx context.Context, root *WorkerNodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wns.fns))
	for _, fn := range wns.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wns.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
