// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)

// WorkerNode is the predicate function for workernode builders.
type WorkerNode func(*sql.Selector)
